### ISSUE TITLE
Unrecognized field name "feature_scaling_method"

### ISSUE THREAD

**Issue by iamdank** [mehditeimouri-UT/Fragments-Expert#1]
For Fragments-Expert: 
Learning >> Train decision Model >> {SVM, Naive Bayes, LDA, NN}  --> I receive the following error:

Unrecognized field name "feature_scaling_method".

with output example:
"Error in Display_DecisionMachine_FFC (line 83)
        GUI_MainEditBox_Update_FFC(false,sprintf('Method of Feature Scaling: %s',TrainingParameters.feature_scaling_method));

Error in Script_DecisionMachine_Train_FFC (line 444)
Display_DecisionMachine_FFC(TrainingParameters,TrainingResults,DecisionMachine,DecisionMachine_CL,ClassLabels)

Error in Main_FFC>RunMethodsforMenus_FFC (line 243)
        ErrorMsg = Script_DecisionMachine_Train_FFC;
 
Error while evaluating Menu Callback."

This is using MATLAB 2021a. Interestingly, Decision Tree, Random Forest and Ensemble kNN seem unaffected.

I am currently downloading 2015b to see if the problem persists in the older version.

**Comment by iamdank** [comment]
For each occurrence (line xx) error, I replaced "feature_scaling_method" (where applicable)  with "feature_scaling_FFCthod"
That seems to 'resolve' the error. However, I don't know if it is the correct fix.

**Comment by mehditeimouri-UT** [comment]
> 
> 
> For each occurrence (line xx) error, I replaced "feature_scaling_method" (where applicable) with "feature_scaling_FFCthod"
> That seems to 'resolve' the error. However, I don't know if it is the correct fix.

The correction you made is OK. Today, I corrected this problem.

**Comment by mehditeimouri-UT** [comment]
> 
> 
> For Fragments-Expert:
> Learning >> Train decision Model >> {SVM, Naive Bayes, LDA, NN} --> I receive the following error:
> 
> Unrecognized field name "feature_scaling_method".
> 
> with output example:
> "Error in Display_DecisionMachine_FFC (line 83)
> GUI_MainEditBox_Update_FFC(false,sprintf('Method of Feature Scaling: %s',TrainingParameters.feature_scaling_method));
> 
> Error in Script_DecisionMachine_Train_FFC (line 444)
> Display_DecisionMachine_FFC(TrainingParameters,TrainingResults,DecisionMachine,DecisionMachine_CL,ClassLabels)
> 
> Error in Main_FFC>RunMethodsforMenus_FFC (line 243)
> ErrorMsg = Script_DecisionMachine_Train_FFC;
> 
> Error while evaluating Menu Callback."
> 
> This is using MATLAB 2021a. Interestingly, Decision Tree, Random Forest and Ensemble kNN seem unaffected.
> 
> I am currently downloading 2015b to see if the problem persists in the older version.

Thank you very much for the feedback.

**Comment by iamdank** [comment]
Many thanks for the prompt response and for writing this well documented toolbox. It’s difficult to find a digital forensics open source tool that is actively maintained. Issue solved.
